name: html_text
description: convert html text to text by putting italics, bold and underline
version: 0.0.3
homepage: https://github.com/matheusperez/html_text

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
