name: html_text
description: convert html text to text by putting italics, bold and underline
version: 0.0.1
homepage: https://github.com/matheusperez/html_text

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
